---
title: "Blood and Wine: The Wild Hunt"
output: 
  flexdashboard::flex_dashboard:
runtime: shiny
---
  
```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(readr)
library(ggplot2)

# UTF fix

source.utf8 <- function(f) {
    l <- readLines(f, encoding="UTF-8")
    eval(parse(text=l),envir=.GlobalEnv)
}

# include helper

source("r/topic_selections.r")
source("r/app_page1.r")

# load data
wine_file <- read_csv("data/wine_master.utf8.csv")
wine_master <- wine_file[,c(24,26:33)]
wine_lda <- wine_file[,4:24]
wine_clusters <- wine_file[,2:4]
wine_bottles <- read_csv("data/wine_betas.utf8.csv")
mapPolys <- geojsonio::geojson_read("data/countries.geo.json", what = "sp")
names(mapPolys) = c("id","country")
#mergedMap = sp::merge(mapPolys,wine_master)
geographical_freqs = as.data.frame(sort(table(wine_master$country), decreasing=T))
names(geographical_freqs) = c("Country","N")
countries_by_freq = geographical_freqs$Country


```

Identify your favourite flavours >> {data-orientation=rows}
===============================================================
Row {data-height=25}
--------------------------
Didn't you know there are many many ways to look at wine? Explore some ways below.

Row {data-height=50 data-width=100%}
------------------------------------
Show me X countries, where X =

```{r}
numericInput("numCountries", "", 5, 1, length(countries_by_freq), width='50px')

displayCountries <- reactive({countries_by_freq[1: input$numCountries,]})
```

Row {data-height=500 .tabset .tabset-fade}
--------------------------

### Pricing

```{r}
page_1_price_dist(wine_master)

```

### Variety

```{r}
page_1_variety_dist(wine_master)
```

### Review Ratings

```{r}
page_1_ratings_dist(wine_master)
```

### Country
```{r}
page_1_country_dist(wine_master)
```

Sample the relationships >> {data-orientation=rows}
===================================================

Row {data-height = 150}
------------------------

See how the different brands are related to each other

Row {.tabset, data-height = 500}
--------------------------------
### Prices for different countries

```{r}

```

### Ratings for different prices

```{r}
```

### Ratings for different varieties

```{r}
```

Locate your favourite flavours >>
=================================
Inputs {.sidebar}
---------------------------------------------------------------------
```{r}
topic_suggestions = wine_topic_suggestions(wine_bottles)
textInput("searchTerm", "Search:")
selectInput("topicSelection","Topic", choices=topic_suggestions(), selected="topic1", selectize=FALSE)
```

Column
-----------------------------------------------------------------------

```{r}
chloro = make.chloropleth(wine_lda)
chloro()
```


And now ... Drink and view the entire array!{data-orientation=columns}
======================================================================
Inputs {.sidebar}
---------------------------------------------------------------------------------
```{r}

numericInput(inputId = "labels", label = "Number of Labels", min = 50, max = nrow(wine_master), value= 500)

```

Column
--------------------------------------------------------------------------------
```{r}
renderTable({
  wine_sample <- sample(nrow(wine_master), as.integer(input$labels))
  wine_master[wine_sample,]
})

```